export const VIEW_THUMBNAIL = `VIEW_THUMBNAIL`;
export const VIEW_PORTRAIT = `VIEW_PORTRAIT`;

export const AWS_LOGIN_ATTEMPT = `AWS_LOGIN_ATTEMPT`;
export const AWS_LOGIN_SUCCESSFUL = `AWS_LOGIN_SUCCESSFUL`;
export const AWS_LOGIN_FAILED = `AWS_LOGIN_FAILED`;

export const AWS_LOGOUT_ATTEMPT = `AWS_LOGOUT_ATTEMPT`;
export const AWS_LOGOUT_SUCCESSFUL = `AWS_LOGOUT_SUCCESSFUL`;
export const AWS_LOGOUT_FAILED = `AWS_LOGOUT_FAILED`;

export const AWS_SIGNUP_ATTEMPT = `AWS_SIGNUP_ATTEMPT`;
export const AWS_SIGNUP_SUCCESSFUL = `AWS_SIGNUP_SUCCESSFUL`;
export const AWS_SIGNUP_FAILED = `AWS_SIGNUP_FAILED`;

export const AWS_CONFIRM_SIGNUP_ATTEMPT = `AWS_CONFIRM_SIGNUP_ATTEMPT`;
export const AWS_CONFIRM_SIGNUP_SUCCESSFUL = `AWS_CONFIRM_SIGNUP_SUCCESSFUL`;
export const AWS_CONFIRM_SIGNUP_FAILED = `AWS_CONFIRM_SIGNUP_FAILED`;

export const AWS_POST_PHOTO_ATTEMPT = `AWS_POST_PHOTO_ATTEMPT`;
export const AWS_POST_PHOTO_SUCCESSFUL = `AWS_POST_PHOTO_SUCCESSFUL`;
export const AWS_POST_PHOTO_FAILED = `AWS_POST_PHOTO_FAILED`;