export const THUMBNAIL_VIEW = `THUMBNAIL_VIEW`;
export const PORTRAIT_VIEW = `PORTRAIT_VIEW`;

export const ATTEMPT_AWS_LOGIN = `ATTEMPT_AWS_LOGIN`;
export const SUCCESSFUL_AWS_LOGIN = `SUCCESSFUL_AWS_LOGIN`;
export const FAILED_AWS_LOGIN = `FAILED_AWS_LOGIN`;

export const ATTEMPT_AWS_LOGOUT = `ATTEMPT_AWS_LOGOUT`;
export const SUCCESSFUL_AWS_LOGOUT = `SUCCESSFUL_LOGOUT`;
export const FAILED_AWS_LOGOUT = `FAILED_LOGOUT`;

export const SUCCESSFUL_AWS_SIGNUP = `SUCCESSFUL_AWS_SIGNUP`;
export const FAILED_AWS_SIGNUP = `FAILED_AWS_SIGNUP`;
export const ATTEMPT_AWS_SIGNUP = `ATTEMPT_AWS_SIGNUP`;

export const ATTEMPT_AWS_CONFIRM_SIGNUP = `ATTEMPT_AWS_CONFIRM_SIGNUP`;
export const SUCCESSFUL_AWS_CONFIRM_SIGNUP = `SUCCESSFUL_AWS_CONFIRM_SIGNUP`;
export const FAILED_AWS_CONFIRM_SIGNUP = `FAILED_AWS_CONFIRM_SIGNUP`;

export const ATTEMPT_AWS_POST_PHOTO = `ATTEMPT_AWS_POST_PHOTO`;
export const SUCCESSFUL_AWS_POST_PHOTO = `SUCCESSFUL_AWS_POST_PHOTO`;
export const FAILED_AWS_POST_PHOTO = `FAILED_AWS_POST_PHOTO`;