export const THUMBNAIL_VIEW = `THUMBNAIL_VIEW`;
export const PORTRAIT_VIEW = `PORTRAIT_VIEW`;
export const ATTEMPT_AWS_LOGIN = `ATTEMPT_AWS_LOGIN`;
export const SUCCESSFUL_AWS_LOGIN = `SUCCESSFUL_AWS_LOGIN`;
export const FAILED_AWS_LOGIN = `FAILED_AWS_LOGIN`;
export const LOGOUT = `LOGOUT`;