export const THUMBNAIL_VIEW = `THUMBNAIL_VIEW`;
export const PORTRAIT_VIEW = `PORTRAIT_VIEW`;
export const ATTEMPT_FB_LOGIN = `ATTEMPT_FB_LOGIN`;
export const SUCCESSFUL_FB_LOGIN = `SUCCESSFUL_FB_LOGIN`;
export const LOGOUT = `LOGOUT`;